name: web-app ci-cd
on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, closed]
    branches: [main, master]

jobs:
  build-test-deliver-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "^3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user pipenv
          pipenv --python $(which python)
          pipenv install pytz
          pipenv install python-dateutil
          pipenv install build
          pipenv install requests
          pipenv install flask
          pipenv install pytest
          pipenv install gitcommitlogger
          pipenv install bson
          pipenv install pymongo

      - name: Build docker images
        run: |
          docker build -t avachani/plant-recog:web-app ./web-app
      

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push avachani/plant-recog:web-app

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Deploy to Digital Ocean
        run: |
          ssh -o StrictHostKeyChecking=no root@64.225.51.26 << 'EOF'
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker pull ${{ secrets.DOCKER_USERNAME }}/plant-recog:web-app
            docker stop web-app || true
            docker rm web-app || true
            docker run --name web-app -d -p 5000:5000 --env-file /root/.env ${{ secrets.DOCKER_USERNAME }}/plant-recog:web-app
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Test 
        run: |
          pipenv run pytest